apiVersion: v2
description: An automated observability platform for cloud-native developers.
name: stella-agent-ce
engine: gotpl
type: application
version: 6.5.001
appVersion: "6.5.0"
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/deepflowio/deepflow
home: https://github.com/deepflowio/deepflow
keywords:
  - deepflow
icon: https://raw.githubusercontent.com/deepflowio/deepflow-charts/main/deepflow.svg
maintainers:
  - name: deepflow
    url: https://github.com/deepflowio/deepflow
